### ISSUE TITLE
station order is lost when querying multiple stations in ki_timeseries_values()

### ISSUE THREAD

**Issue by jimmybom** [rywhale/kiwisR#10]
Hi Ryan,
Great package. The LWCB just got Wiski and I'm excited to plug it into R. I ran into an issue where I query multiple ts_id's in the ki_timeseries_values() function. It returns a tibble, with the data in no particular order. I would suggest either ensuring the order is the same as the vector of ts_id's input into the function, or adding a new column with the ts_id (currently only the name is exported). For now, I'm just going to call the function with an individual ts_id (either with a loop or lapply)
cheers,
James
jbomhof@lwcb.ca

**Comment by jimmybom** [comment]
Yes, I think that is a great idea.

**Comment by rywhale** [comment]
To do: 
* [ ] Add `station_id` and `ts_id` to metadata return fields here https://github.com/rywhale/kiwisR/blob/c7ac1ef392f3e2f5e62ef3cc0699aa8d1cfd677b/R/ki_timeseries_values.R#L57-L66
* [ ] Adapt unit tests for `ki_timeseries_values` where needed
* [ ] Up version, run checks and submit to CRAN

**Comment by rywhale** [comment]
@jimmybom Did a quick fix for this, you can download the development version from GitHub for now. 
```{r}
remotes::install_github("rywhale/kiwisR")
```
Leaving the issue open as I'd eventually like to add `md_return_fields` as an optional argument in `ki_timeseries_values` to allow the user to specify whatever metadata they want. The default metadata return fields will be as they are in the most recent dev version, i.e.: 
  * station_name
  * station_id
  * ts_name
  * ts_id
  * Units

**Comment by jimmybom** [comment]
Great, thanks!
